---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

## specify the namespace to create the polcies/placements/bindings in
namespace: policies-hub-prod

transformers:
  ## set the name of the PolicySets to include a suffix specific to this environment
  - policyset-suffixer.yml


## Add the local resources to the set
resources:
  - managedclusterset.yml
  - managedcluster.yml  ###  This adds the hub cluster to this clusterset.
  - ../../policies/common/acm-placements/ocp


components:
  - ../../policy-groups/ocp-common
  - ../../policy-groups/acm-hub/

  ## base must be added last to the list of components
  - ../../base
