---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - ../../policies/ocp/cluster-configs/cluster-autoscaling/
  - ../../policies/ocp/operators/cert-manager
  - ../../policies/ocp/operators/gatekeeper
  - ../../policies/ocp/operators/gitops
