---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - ../../policies/acm/ensure-placement-toleration
  - ../../policies/acm/feature-flags-placement
  - ../../policies/acm/klusterlet-infra
  - ../../policies/acm/managedserviceaccount
  - ../../policies/acm/policy-alerts
  - ../../policies/ocp/operators/acm
