---
name: Policy-Checks

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ 'main' ]

defaults:
  run:
    shell: bash
    working-directory: acm-policies

jobs:
  validation-tests:
    runs-on: ubuntu-latest
    container:
      image: registry.access.redhat.com/ubi9/go-toolset:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: acm-policies

      - name: Verify Policies
        run: |
          ./build/validate-policies.sh

      - name: Verify File Whitespace
        run: |
          ./build/validate-trailing-whitespace.sh

      - name: Verify Yaml starts with doc
        run: |
          ./build/validate-yaml-doc.sh

      - name: Verify file ends in newline
        run: |
          ./build/validate-end-of-file.sh
